#!/usr/bin/env bash
PRG="$0"

# need this for relative symlinks
while [ -h "$PRG" ] ; do
   PRG=`readlink "$PRG"`
done

scriptdir=`dirname "$PRG"`

export PYTHONSTARTUP=$scriptdir/harrypotter.py

$scriptdir/nagini-python/python.exe

export PYTHONSTARTUP=""
